/* Additional record code for Flags_loadFlags generated by the OpenModelica Compiler 1.8.1 (r11556). */
#include "meta_modelica.h"
#define Error_MessageType_SYNTAX__desc_added 1
const char* Error_MessageType_SYNTAX__desc__fields[1] = {"no fileds"};
struct record_description Error_MessageType_SYNTAX__desc = {
  "Error_MessageType_SYNTAX", /* package_record__X */
  "Error.MessageType.SYNTAX", /* package.record_X */
  Error_MessageType_SYNTAX__desc__fields
};
#define Error_MessageType_GRAMMAR__desc_added 1
const char* Error_MessageType_GRAMMAR__desc__fields[1] = {"no fileds"};
struct record_description Error_MessageType_GRAMMAR__desc = {
  "Error_MessageType_GRAMMAR", /* package_record__X */
  "Error.MessageType.GRAMMAR", /* package.record_X */
  Error_MessageType_GRAMMAR__desc__fields
};
#define Error_MessageType_SYMBOLIC__desc_added 1
const char* Error_MessageType_SYMBOLIC__desc__fields[1] = {"no fileds"};
struct record_description Error_MessageType_SYMBOLIC__desc = {
  "Error_MessageType_SYMBOLIC", /* package_record__X */
  "Error.MessageType.SYMBOLIC", /* package.record_X */
  Error_MessageType_SYMBOLIC__desc__fields
};
#define Error_MessageType_SIMULATION__desc_added 1
const char* Error_MessageType_SIMULATION__desc__fields[1] = {"no fileds"};
struct record_description Error_MessageType_SIMULATION__desc = {
  "Error_MessageType_SIMULATION", /* package_record__X */
  "Error.MessageType.SIMULATION", /* package.record_X */
  Error_MessageType_SIMULATION__desc__fields
};
#define Error_MessageType_SCRIPTING__desc_added 1
const char* Error_MessageType_SCRIPTING__desc__fields[1] = {"no fileds"};
struct record_description Error_MessageType_SCRIPTING__desc = {
  "Error_MessageType_SCRIPTING", /* package_record__X */
  "Error.MessageType.SCRIPTING", /* package.record_X */
  Error_MessageType_SCRIPTING__desc__fields
};
#define Error_Severity_WARNING__desc_added 1
const char* Error_Severity_WARNING__desc__fields[1] = {"no fileds"};
struct record_description Error_Severity_WARNING__desc = {
  "Error_Severity_WARNING", /* package_record__X */
  "Error.Severity.WARNING", /* package.record_X */
  Error_Severity_WARNING__desc__fields
};
#define Error_Severity_NOTIFICATION__desc_added 1
const char* Error_Severity_NOTIFICATION__desc__fields[1] = {"no fileds"};
struct record_description Error_Severity_NOTIFICATION__desc = {
  "Error_Severity_NOTIFICATION", /* package_record__X */
  "Error.Severity.NOTIFICATION", /* package.record_X */
  Error_Severity_NOTIFICATION__desc__fields
};
#define Flags_FlagData_REAL__FLAG__desc_added 1
const char* Flags_FlagData_REAL__FLAG__desc__fields[1] = {"data"};
struct record_description Flags_FlagData_REAL__FLAG__desc = {
  "Flags_FlagData_REAL__FLAG", /* package_record__X */
  "Flags.FlagData.REAL_FLAG", /* package.record_X */
  Flags_FlagData_REAL__FLAG__desc__fields
};
#define Flags_Flags_FLAGS__desc_added 1
const char* Flags_Flags_FLAGS__desc__fields[2] = {"debugFlags","configFlags"};
struct record_description Flags_Flags_FLAGS__desc = {
  "Flags_Flags_FLAGS", /* package_record__X */
  "Flags.Flags.FLAGS", /* package.record_X */
  Flags_Flags_FLAGS__desc__fields
};
#define Error_Message_MESSAGE__desc_added 1
const char* Error_Message_MESSAGE__desc__fields[4] = {"id","ty","severity","message"};
struct record_description Error_Message_MESSAGE__desc = {
  "Error_Message_MESSAGE", /* package_record__X */
  "Error.Message.MESSAGE", /* package.record_X */
  Error_Message_MESSAGE__desc__fields
};
#define Error_Severity_ERROR__desc_added 1
const char* Error_Severity_ERROR__desc__fields[1] = {"no fileds"};
struct record_description Error_Severity_ERROR__desc = {
  "Error_Severity_ERROR", /* package_record__X */
  "Error.Severity.ERROR", /* package.record_X */
  Error_Severity_ERROR__desc__fields
};
#define Error_MessageType_TRANSLATION__desc_added 1
const char* Error_MessageType_TRANSLATION__desc__fields[1] = {"no fileds"};
struct record_description Error_MessageType_TRANSLATION__desc = {
  "Error_MessageType_TRANSLATION", /* package_record__X */
  "Error.MessageType.TRANSLATION", /* package.record_X */
  Error_MessageType_TRANSLATION__desc__fields
};
#define Flags_FlagVisibility_INTERNAL__desc_added 1
const char* Flags_FlagVisibility_INTERNAL__desc__fields[1] = {"no fileds"};
struct record_description Flags_FlagVisibility_INTERNAL__desc = {
  "Flags_FlagVisibility_INTERNAL", /* package_record__X */
  "Flags.FlagVisibility.INTERNAL", /* package.record_X */
  Flags_FlagVisibility_INTERNAL__desc__fields
};
#define Flags_FlagData_INT__FLAG__desc_added 1
const char* Flags_FlagData_INT__FLAG__desc__fields[1] = {"data"};
struct record_description Flags_FlagData_INT__FLAG__desc = {
  "Flags_FlagData_INT__FLAG", /* package_record__X */
  "Flags.FlagData.INT_FLAG", /* package.record_X */
  Flags_FlagData_INT__FLAG__desc__fields
};
#define Flags_ValidOptions_STRING__DESC__OPTION__desc_added 1
const char* Flags_ValidOptions_STRING__DESC__OPTION__desc__fields[1] = {"options"};
struct record_description Flags_ValidOptions_STRING__DESC__OPTION__desc = {
  "Flags_ValidOptions_STRING__DESC__OPTION", /* package_record__X */
  "Flags.ValidOptions.STRING_DESC_OPTION", /* package.record_X */
  Flags_ValidOptions_STRING__DESC__OPTION__desc__fields
};
#define Flags_FlagData_STRING__LIST__FLAG__desc_added 1
const char* Flags_FlagData_STRING__LIST__FLAG__desc__fields[1] = {"data"};
struct record_description Flags_FlagData_STRING__LIST__FLAG__desc = {
  "Flags_FlagData_STRING__LIST__FLAG", /* package_record__X */
  "Flags.FlagData.STRING_LIST_FLAG", /* package.record_X */
  Flags_FlagData_STRING__LIST__FLAG__desc__fields
};
#define Flags_FlagData_ENUM__FLAG__desc_added 1
const char* Flags_FlagData_ENUM__FLAG__desc__fields[2] = {"data","validValues"};
struct record_description Flags_FlagData_ENUM__FLAG__desc = {
  "Flags_FlagData_ENUM__FLAG", /* package_record__X */
  "Flags.FlagData.ENUM_FLAG", /* package.record_X */
  Flags_FlagData_ENUM__FLAG__desc__fields
};
#define Flags_ValidOptions_STRING__OPTION__desc_added 1
const char* Flags_ValidOptions_STRING__OPTION__desc__fields[1] = {"options"};
struct record_description Flags_ValidOptions_STRING__OPTION__desc = {
  "Flags_ValidOptions_STRING__OPTION", /* package_record__X */
  "Flags.ValidOptions.STRING_OPTION", /* package.record_X */
  Flags_ValidOptions_STRING__OPTION__desc__fields
};
#define Flags_FlagData_BOOL__FLAG__desc_added 1
const char* Flags_FlagData_BOOL__FLAG__desc__fields[1] = {"data"};
struct record_description Flags_FlagData_BOOL__FLAG__desc = {
  "Flags_FlagData_BOOL__FLAG", /* package_record__X */
  "Flags.FlagData.BOOL_FLAG", /* package.record_X */
  Flags_FlagData_BOOL__FLAG__desc__fields
};
#define Flags_ConfigFlag_CONFIG__FLAG__desc_added 1
const char* Flags_ConfigFlag_CONFIG__FLAG__desc__fields[7] = {"index","name","shortname","visibility","defaultValue","validOptions","description"};
struct record_description Flags_ConfigFlag_CONFIG__FLAG__desc = {
  "Flags_ConfigFlag_CONFIG__FLAG", /* package_record__X */
  "Flags.ConfigFlag.CONFIG_FLAG", /* package.record_X */
  Flags_ConfigFlag_CONFIG__FLAG__desc__fields
};
#define Flags_FlagData_STRING__FLAG__desc_added 1
const char* Flags_FlagData_STRING__FLAG__desc__fields[1] = {"data"};
struct record_description Flags_FlagData_STRING__FLAG__desc = {
  "Flags_FlagData_STRING__FLAG", /* package_record__X */
  "Flags.FlagData.STRING_FLAG", /* package.record_X */
  Flags_FlagData_STRING__FLAG__desc__fields
};
#define Flags_FlagVisibility_EXTERNAL__desc_added 1
const char* Flags_FlagVisibility_EXTERNAL__desc__fields[1] = {"no fileds"};
struct record_description Flags_FlagVisibility_EXTERNAL__desc = {
  "Flags_FlagVisibility_EXTERNAL", /* package_record__X */
  "Flags.FlagVisibility.EXTERNAL", /* package.record_X */
  Flags_FlagVisibility_EXTERNAL__desc__fields
};
#define Flags_FlagData_EMPTY__FLAG__desc_added 1
const char* Flags_FlagData_EMPTY__FLAG__desc__fields[1] = {"no fileds"};
struct record_description Flags_FlagData_EMPTY__FLAG__desc = {
  "Flags_FlagData_EMPTY__FLAG", /* package_record__X */
  "Flags.FlagData.EMPTY_FLAG", /* package.record_X */
  Flags_FlagData_EMPTY__FLAG__desc__fields
};
#define Flags_DebugFlag_DEBUG__FLAG__desc_added 1
const char* Flags_DebugFlag_DEBUG__FLAG__desc__fields[3] = {"index","name","description"};
struct record_description Flags_DebugFlag_DEBUG__FLAG__desc = {
  "Flags_DebugFlag_DEBUG__FLAG", /* package_record__X */
  "Flags.DebugFlag.DEBUG_FLAG", /* package.record_X */
  Flags_DebugFlag_DEBUG__FLAG__desc__fields
};

