# Makefile generated by OpenModelica

# Dynamic loading uses -O0 by default
SIM_OR_DYNLOAD_OPT_LEVEL=-O0
CC=gcc
CXX=g++
LINK=g++ -shared -export-dynamic
EXEEXT=.exe
DLLEXT=.dll
CFLAGS= -I"C:/OpenModelica1.8.0/include/omc"  ${SIM_OR_DYNLOAD_OPT_LEVEL} -falign-functions -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}
LDFLAGS= -L"C:/OpenModelica1.8.0/lib/omc" -lSimulationRuntimeC -lregex -lexpat
SENDDATALIBS= -static-libgcc -luuid -lole32 -lws2_32
PERL=perl
MAINFILE=LexerGenerator_getCurrentTimeStr.conv.c

.PHONY: LexerGenerator_getCurrentTimeStr
LexerGenerator_getCurrentTimeStr: $(MAINFILE) LexerGenerator_getCurrentTimeStr.h LexerGenerator_getCurrentTimeStr_records.c
	 $(CC) $(CFLAGS) -c -o LexerGenerator_getCurrentTimeStr.o $(MAINFILE)
	 $(CC) $(CFLAGS) -c -o LexerGenerator_getCurrentTimeStr_records.o LexerGenerator_getCurrentTimeStr_records.c
	 $(LINK) -o LexerGenerator_getCurrentTimeStr$(DLLEXT) LexerGenerator_getCurrentTimeStr.o LexerGenerator_getCurrentTimeStr_records.o -lomcruntime -liconv -lexpat -lsqlite3 -llpsolve55 -lmico2313 -lws2_32 -lregex -llapack-mingw -ltmglib-mingw -lblas-mingw -lf2c $(CFLAGS) $(LDFLAGS) $(SENDDATALIBS) -lm
LexerGenerator_getCurrentTimeStr.conv.c: LexerGenerator_getCurrentTimeStr.c
	 $(PERL) C:/OpenModelica1.8.0/share/omc/scripts/convert_lines.pl $< $@.tmp
	 @mv $@.tmp $@