all:
	# 01 is too slow at the moment
	# make -C 01_experiment -f Makefile.omc test
	make -C 02a_exp1 -f Makefile.omc test
	make -C 02b_exp2 -f Makefile.omc test
	make -C 03_assignment test
	make -C 04a_assigntwotype test
	make -C 04b_modassigntwotype test
