all:
	# 01 is too slow at the moment
	# make -C 01_experiment test
	make -C 02a_exp1 test
	make -C 02b_exp2 test
	make -C 03_assignment test
	make -C 04a_assigntwotype test
	make -C 04b_modassigntwotype test
