SRCPATH=$(OMDEV)\lib\antlr-win32-msvc
INCLPATH=$(OMDEV)\include
CPPFLAGS=/Ob2 /Ox /O2 /Ot /GL /Oy /I $(INCLPATH) /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /GS /Fd"antlr.pdb" /W3 /nologo /c /Zi /TP
SRCS=$(SRCPATH)\*.cpp
OBJS=*.obj


all: antlr.lib

antlr.lib: $(OBJS)
	@move /Y dll.obj dll.ob_
	lib.exe /LTCG /OUT:"antlr.lib" /NOLOGO *.obj
	@move /Y dll.ob_ dll.obj

$(OBJS):$(SRCS)
	$(CC) $(CPPFLAGS) $(SRCS)

clean:
	del /Q $(OBJS) antlr.lib *.idb *.pdb
