CLEAN=Absyn.c Absyn.h Absyn.o Absyn.srz Emit.c Emit.h Emit.o Emit.srz Main.c Main.h Main.o Main.srz Mcode.c Mcode.h Mcode.o Mcode.srz ParseRML.o Parse.srz Trans.c Trans.h Trans.o Trans.srz
HEADERS=Absyn.h
OBJS=Absyn.o Emit.o Main.o Mcode.o ParseRML.o Trans.o lexer.o parser.o
include ../common.rml
