#!/bin/sh

successes=0
total=0
verbose=no

runone ()
{
    f=$1
    
    log=/tmp/log-$f
    
    ../modeq $f >$log 2>&1;
    
    if [ $? -ne 0 ]; then
	echo nonzero exit status
	return 1
    fi
    
    if egrep '^#|Execution failed!' $log; then
#	echo Log saved in $log
	return 1
    fi

    tmp1=/tmp/equations-1
    tmp2=/tmp/equations-2

    cp $log $tmp1
    ed $tmp1 >/dev/null 2>&1 <<EOF
1,/^equations/d
1d
/^\$/,\$d
w
q
EOF

    cut -c 4- $f > $tmp2
    ed $tmp2 >/dev/null 2>&1 <<EOF
1,/^Equations:/d
1d
/^\$/,\$d
w
q
EOF

    sort $tmp1 > $tmp1-sorted
    sort $tmp2 > $tmp2-sorted

    diff -w $tmp1-sorted $tmp2-sorted > $tmp1

    if [ $? != 0 ]; then
	  echo "equation mismatch"
	  echo >> $log
	  echo Equation diff: >> $log
	  sed -n -e 's/^>\(.*\)/expected:\1/p' \
		 -e 's/^<\(.*\)/got:     \1/p' \
	      < $tmp1 >> $log
	  return 1
    fi
    return 0
}

if [ $1 = "-v" ]; then
    verbose=yes
    shift
fi

for f in $*; do
    printf "  %-24s... " $f
    total=`expr $total + 1`
    runone $f
    if [ $? -eq 0 ]; then
	printf 'ok\n'
	successes=`expr $successes + 1`
    else
	if [ $verbose = yes ]; then
	    echo
	    echo ==== Log $log
	    cat $log
	fi
#	printf 'failed\n'
    fi
done

printf '\n== %d out of %d tests succeeded\n' $successes $total
