#Makefile generated by OpenModelica

CXX=g++
BouncingBall: BouncingBall.cpp
	 $(CXX) -o BouncingBall.exe BouncingBall.cpp -L"C:\Modelica\OpenModelicaSources\svns\build/lib/" -I. -I"C:\Modelica\OpenModelicaSources\svns\build/include/"  -lsim -lg2c -lc_runtime 
